version: '3'

services:
  server:
    container_name: snake-game-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - network

networks:
  network:
    driver: bridge
  