# NOTE, THIS IS NOT A GOOD WAY OF KEEPING SECRET. THIS FILE SHOULD BE HIDDEN. (ADDITIONALY, NOT THE SAFEST PASSWORD MEASURES ARE IN PLACE).

PASSWORD_SALT = 'jFr3shWjERHj6M4eE0fU'

JWT_SECRET = 'Vct6GGjJ8LKcBwjSNAzY'