# NOTE, THIS IS NOT A GOOD WAY OF KEEPING SECRET. THIS FILE SHOULD BE HIDDEN. (ADDITIONALY, NOT THE SAFEST PASSWORD MEASURES ARE IN PLACE).

PASSWORD_SALT = 'tbmlu6IIGxOfvlBfGwy9'

JWT_SECRET = 'GyjahwU4F6XsWJ5QQVFX'